### PR TITLE
search for sync token

### PR DESCRIPTION
**Pull request by faljse**
Modified from #85 discussion
Works for me :)

### CODE REVIEW

**Comment by faljse** [comment]
Sometimes locks up at: https://github.com/phoboslab/jsmpeg/blob/master/src/mpeg1.js#L749

**Comment by phoboslab** [comment]
After a bit of digging, MPEG-TS seems to dictate that to find synchronization, you have to detect **5** consecutive `0x47` sync tokens with a distance of 188 bytes each. I.e. if you find a sync token, repeat to check `byteIndex+187` for `0x47` 4 times.

See for example: https://linuxtv.org/wiki/index.php/MPEG-2_Frame_Aligner

**Comment by faljse** [comment]
Done :)
I did quite a bit of testing today, and it works pretty reliable.

It might be a good idea to add some error recovery for things like the while(true) in decodeBlock()
(Maybe throw an exception and resync if we read() beyond the buffer in BitBuffer).
But for now this works well enough for me.

**Comment by phoboslab** [comment]
Thanks!

**Pull request closed without merging**
