### PR TITLE
Make it npm ready!

### PR DESCRIPTION
**Pull request by nulltask**
I added some tweaks.

- Added package.json: You can ready to publish to npmjs.org.
- Build with webpack: The distribution followings UMD module pattern.

### CODE REVIEW

**Comment by phoboslab** [comment]
Thanks for you work, but I'm sorry to say that I will not merge this.

1. I don't understand why a single file frontend lib has to be published on npm
2. I don't like the fact that you _need_ a preprocessor (for UMD); you can now longer just load the source files through `<script>` tags.
3. I don't like webpack or build tools in general (I ranted a bit about it in my blog: [see Build Tools & The JavaScript Ecosystem](http://phoboslab.org/log/2017/02/decode-it-like-its-1999))
4. I don't want to maintain an npm package or webpack built step in this repo

In the long run, this would makes the lib less flexible and more work to maintain.

**Comment by nulltask** [comment]
I see your blog post now and I understood your principle. I'm sorry for pull requests contrary to your policy. Thanks for your great works!

**Comment by botverse** [comment]
@phoboslab I understand completely your point, this is very tedious:

```
xcode => homebrew => node => npm => webpack => babel
```

The one good thing in the npm ecosystem is that libraries are very easily reusable:

```javascript
var Player = require('jsmpeg/Player');
var MyDecoder = require('mydecoder');

var decoder = new MyDecoder();
var player = new Player({ decoder });
```

There are some minimal changes that you could do to the Player constructor to accept other video decoders for example, but that would make very easy for other people to build stuff on top of your library. I thought @nulltask's PR was a good thing.

**Comment by phoboslab** [comment]
I agree that the PR was excellent from a technical perspective. Your argument about reusability is of course valid for development. I'm just trying to keep this as simple as possible for _users_ of this library.

**Comment by ambientlight** [comment]
As simple as possible for _users_ of this library would be to actually have it available on npm. 
Might be a great idea to have a polished fork with updated README from like 
[nulltask:feature/npm-ready](https://github.com/nulltask/jsmpeg/tree/feature/npm-ready) that can be maintained separately.

**Comment by niftylettuce** [comment]
@phoboslab I'd gladly help maintain NPM package and all that stuff incl `package.json`, lmk!

**Comment by notiv-nt** [comment]
import JSMpeg from '!!imports-loader?this=>window!exports-loader?JSMpeg!jsmpeg/jsmpeg.min.js';

**Pull request closed without merging**
